FROM node:20-alpine AS deps
WORKDIR /app
ENV NODE_ENV=development
COPY package.json package-lock.json* ./
RUN npm ci

FROM deps AS build
WORKDIR /app
COPY tsconfig.json ./
COPY .editorconfig .prettierrc .eslintrc.cjs vitest.config.ts ./
COPY src ./src
RUN npm run build

FROM node:20-alpine
WORKDIR /app
ENV NODE_ENV=production
COPY --from=build /app/node_modules node_modules
COPY --from=build /app/dist dist
COPY prisma prisma
ENV PORT=3000
EXPOSE 3000
CMD ["sh","-c","npx prisma migrate deploy && node dist/server.js"]
